### ISSUE TITLE
WCxf

### ISSUE THREAD

**Issue by DavidMStraub** [DirectDM/directdm-py#2]
Hi,

I tried to convince @fadybishara that it would be awesome to have an input/output interface to the [Wilson coefficient exchange format (WCxf)](https://wcxf.github.io/). Actually I think it would be fairly straightforward since the classes you have in `wilson_coefficients.py` already contain all of the necessary information as far as I can see. One would have to generate one EFT and one basis file for each EFT (i.e. for each type of DM particle and each number of flavours). One could start of with something like

```python
wc5f = ddm.WC_5f({}, DM_type="D")
# EFT file
print(wcxf.EFT('DMEFT-5', {'dF=0': None}).dump(fmt='yaml'))
# basis file
print(wcxf.Basis('DMEFT-5', 'DirectDM', {'dF=0': {c: None for c in wc3f.wc_name_list}}).dump(fmt='yaml'))
# WC file
print(wcxf.WC('DMEFT-5', 'DirectDM', 91.1876, {'dF=0': wcxf.WC.dict2values(wc3f.coeff_dict)}).dump(fmt='yaml'))
```

If you are interested in this, I'd be happy to discuss it further.

**Comment by jmbrod** [comment]
This is a good suggestion. 

Currently, there are some implicit assumptions of which EFT is used in the DirectDM code. E.g. depending on the DM mass, a HQET-like EFT for the DM currents is used "behind the scenes". Before we could interface to the WCxf, these choices would have to be made explicit. I haven't found a good solution yet which keeps the usage of the code sufficiently simple. 

These issues will have to be addressed in a future version in any case, and I will keep the interface to WCxf in mind.

**Comment by DavidMStraub** [comment]
Hmm ... as long as your n-flavor classes always know in which EFT they are (Dirac vs Majorana, HQET-like DM or not, etc.), I don't see why this is not trivial (at least for output), since you can define an arbitrary number of EFTs. The EFT files have to be defined only once, and this can also be done by hand. But maybe I'm seeing it too simplistic.

**Comment by jmbrod** [comment]
Currently, the classes don't know exactly in which EFT they are (apart from number of flavors), because it is not (yet) relevant. So there would be no one-to-one correspondence between the WC classes and the EFT files. This might be changed in the future.

**Comment by DavidMStraub** [comment]
OK, closing in the meantime.
